### ISSUE TITLE
Can't change order status from admin

### ISSUE THREAD

**Issue by alesdotio** [awesto/django-shop#246]
Admins cannot change the order status to "shipped" when an order was completed and paid. The bug was introduced in 0.2.0 by #227 

@jrief can you provide more reasoning behind https://github.com/divio/django-shop/pull/227/files#L0R55? Wouldn't just setting the order status manually cover your use case?

**Comment by davesque** [comment]
I agree with @alesdotio on this one.  I don't think that kind of specific behavior should be in the default admin class.  If it _really_ has to be in there, it should at least be moved into its own mixin class so you can still easily subclass the base admin with all the default admin properties but without the state-checking behavior in `save_model`.

I recently upgraded from an old version of django-shop to the latest pypi version.  Shortly thereafter, my shop administrator came to me complaining that he couldn't mark anything as shipped.  Now, since I prefer to stick with the latest version on pypi, the only correct option I have is to copy and paste the default admin class from the package code and simply delete the `save_model` method from the class definition.  I could also make a subclass and define a `save_model` that calls the super method of the parent class, but that's really not a good idea.  This makes me feel like this approach is flawed since you have no proper recourse if you want to change the behavior in `save_model` on the default admin.

**Comment by jrief** [comment]
BTW, my fork https://github.com/jrief/django-shop now does it as @alesdotio propoeses.
There are several workflow mixins and a finite state machine which allow state transistions where appropriate, and disallows them where not.

This prevents a shop administrator to change the state from, say "orderd" to "shipping", without having received any payment. The FSM is programmable in the sense, that you now can add various workflow plugin in yours settings.py

**Comment by jrief** [comment]
Closed. Please check version 0.9.
