### ISSUE TITLE
[Question] Dashboard & who is behind the project?

### ISSUE THREAD

**Issue by maltitco** [awesto/django-shop#304]
1. django-shop has its own dashboard or use only the Django admin?

2. Previously, the project was run by DIVO and now I see that it is hooked into AWESTO. You can write something about this change?

**Comment by jrief** [comment]
1. django-shop uses the Django admin. This feature is mandatory, because its coupled tightly to django-cms, which also uses Django admin. Moreover, since product models are freely declarable by the merchant implementing its site, we somehow need a generic way to manage arbitrary models.

If you have any idea for a kind of alternative dashboard, please let me know.

2. Divio turned that project over to me because they want to focus on django-cms. We are currently three maintainers and we aim to support that framework commercially. Soon there will be a web site explaining our goals and the company behind it. Currently I focus more on features and stability than marketing.
Therefore, if you are planning an e-commerce site, you may contact me directly.

**Comment by maltitco** [comment]
Regarding the dashboard you can be the django admin or add panel the stats and necessary options as it is for example in magento. 


Currently I would like to change the current platform (Magento) for something that I could embrace the same side of the code. In django working for over 2 years and I was able to write a few applications which inclines pass to move commerce platform for django.

I tested: oscar commerce, shoop, and now is testing a new version of django-shop.

In each of the above I have put a lot of work to adjust the Polish conditions (delivery, payment, taxes).
Therefore, my questions because when I decide on one of the platform that I would stay with her a long time ...

**Comment by jrief** [comment]
That sounds great. I'm very interested in helping out and I hope that django-shop will become one of the big players of Django-based e-commerce frameworks.
There is an installable Docker container you can use to play around. Adding extra tax models, shipping and payment conditions is very straight forward and can easily be implemented.
I will be in Budapest on DjangoCon next month and we can meet there. Otherwise please contact me directly via email. I can show you a few features using Google Hangout.

**Comment by maltitco** [comment]
Thank you for the invitation to DjangoCon to Budapest but I can not get away from work. I'll try to describe their impressions after testing django-shop.

**Comment by rfleschenberg** [comment]
I consider this "answered" and will close the isse. Feel free to contact us if you have any further questions!
