### ISSUE TITLE
[suggestion] change the IRC channel on Gitter

### ISSUE THREAD

**Issue by maltitco** [awesto/django-shop#324]
I have a suggestion to change the IRC channel on https://gitter.im.
With several projects already using, it has lots of cool features including notifications.

**Comment by rfleschenberg** [comment]
I have to admit that I prefer traditional IRC with my IRC client over web-based services. But maybe that is just because I am an old fart ;) I guess it would not harm to give gitter a try. I just took a look, but I was not able to create a room for this repository. Maybe only the repository owner (@jrief) can do it.

**Comment by maltitco** [comment]
ok we wait and see what to say the Jacob for idea.

**Comment by rfleschenberg** [comment]
https://gitter.im/awesto/django-shop

See you there :)
