### ISSUE TITLE
BaseCartItem links to Product

### ISSUE THREAD

**Issue by kernom** [awesto/django-shop#350]
For my project I need a cart which is not linked to the product catalogue at all. I.e. I need to serialize the product with all relevant information into the **CartItem**.
Since the **BaseCartItem** is linked to a Product, this is not really possible atm. Could the link to product be moved out to the default implementation of **CartItem**? (Or any other way to avoid this link for people with a similar scenario?)

**Comment by jrief** [comment]
Hmm, interesting use-case.
The BaseCartItems contains a foreign key to product, so that a customer may re-order all the items, from a previous purchase.
May I ask, why you want to get rid of that foreign key?

**Comment by rfleschenberg** [comment]
Can't you just serialize your data into the `CartItem` and simply ignore the foreign key to `Product` in your application?

**Comment by kernom** [comment]
@jrief The product catalog lives in a db managed by an erp (and is not an sql one). Further we cannot guarantee that products will stay in the db (....), but we need customers to be able to keep their old carts and the information therein. 

@rfleschenberg I have considered that and that could be an option to have a dummy product (to satisfy the contraint), but at the same time was wondering whether it's a good idea to work around the given architecture (and I haven't looked into how this would affect cart rendering, yet. I might have to change things to ignore the 'product' ?).

**Comment by rfleschenberg** [comment]
I agree, my suggestion would be more of a workaround than a real solution. I think that in principle, we are open to making django-shop more flexible in this regard, but this needs to be given some thought first.

**Comment by jrief** [comment]
If we make the FK nullable or remove it altogether, the REST serializer responsible for generating the cart's content would not work anymore as expected. We could not determine the line-totals and even worse, we would be unable to determine if an item is already in the cart or must be added.

@kernom if your ERP is running on something not accessible by the Django-ORM, then the (second-)best solution is to write a management command to sync the ERP product model with that of your djangoSHOP instance. Use the same schema to keep it as frictionless as possible.

What kind of database does your ERP use?

**Comment by kernom** [comment]
How about having something like an abstract product manager that would deal with getting this data from the product, so I could have a MyProductManager and feed the required data to django shop?

Unfortunately the syncing solution is out of question as it was decided to not have another point of failure in the existing syncing setup. (Also as we do already have a working catalog, we basically just want to plug the missing parts in )

We are interfacing to it via couchdb.

**Comment by jrief** [comment]
djangoSHOP offers a ``BaseProductManager``. From this you **must** extend your concrete ``ProductManager`` and associate it with your Product models. Actually, djangoSHOP checks if ``MyProduct.objects`` inherits from ``BaseProductManager``.

I then would add a method ``get_queryset()`` to your ProductManager. This then should perform the query on couchdb and while fetching data from there, syncing it with your product model. You should use the product code, or the couchdb-URL as unique product identifiers. This also means that your product model remains really slim, because you can always fetch the missing parts via couchdb.

I assume that you want the clients browser to communicate directly with couchdb, rather than pulling that data through Django. In that case I would override the Product Serializers and add a field which passes the couchdb-URL to the client, so that the browser can fetch the product details. Otherwise, if you want to pull it through Django, use a ``SerializerMethodField``.

Since this is a really interesting use-case, I'd like to be informed on its the project's progress. If you decide to proceed with an alternative solution, please let me also know, so that we can try do better.

Just for curiosity, where are you located and what do you want to sell?
