### ISSUE TITLE
Page calls fail when the shop instance is behind HTTP basic auth

### ISSUE THREAD

**Issue by perplexa** [awesto/django-shop#453]
I have an additional temporary layer of protection in form of a HTTP basic auth in front of the shop instance and noticed that certain calls (login, product list, search) fail with responses similar to:

```
<Response status_code=403, "text/html; charset=utf-8">
{'detail': 'Invalid username/password.'}
```

The error only appeas when you are not logged in to the shop already, as soon as a valid session has been established, this does not occur anymore.

It might be related to django-allauth using the basic auth headers to identify users, but I haven't investigated further but instead replaced the basic auth with a VPN.

While investigating this issue, I also noticed #452

**Comment by jrief** [comment]
> It might be related to django-allauth using the basic auth headers to identify users, but I haven't investigated further but instead replaced the basic auth with a VPN.

Yes, this is because django-SHOP uses DRF, which itself recommends to use the ``allauth.account.auth_backends.AuthenticationBackend``. This uses an HTTP-header ``Authorization: Token ...`` whenever session-based authentication is not available. Since only one such header can be sent, this is incompatible with Basic Authentication. 

I therefore would suggest to create a special filter such as:

```
class AuthFilterBackend(BaseFilterBackend):
    def filter_queryset(self, request, queryset, view):
        customer = Customer.objects.get_from_request(request)
        if customer.is_visitor():
            raise PermissionDenied("Only authenticated customers may access this view")
```

and use it in the urlpatterns for the product's list view:

```
urlpatterns = patterns('',
    url(r'^$', CMSPageProductListView.as_view(
        serializer_class=ProductSummarySerializer,
        filter_backends=[..., AuthFilterBackend, ...],
    )),
```

this will raise a 403-page for visiting (aka anonymous) customers.

**Comment by jrief** [comment]
Can this issue be closed?
TokenAuth and BasicAuth can not work together.
