### ISSUE TITLE
Error while runing manage.py

### ISSUE THREAD

**Issue by leksuss** [awesto/django-shop#501]
Hi! 

I have an error while running manage.py in "example" folder. I use python3.6 on MacOS Sierra.

Here is command:
(mytest) ➜  /Users/andrey/sites/shop/django-shop/example git:(master) ✗ python3 manage.py

Here is error:
`File "/Users/andrey/.envs/mytest/lib/python3.6/enum.py", line 439, in _get_mixins_
    raise TypeError("new enumerations must be created as "
TypeError: new enumerations must be created as "ClassName([mixin_type,] enum_type)"'`

Maybe someone know what is it? 

Thanks!

**Comment by jrief** [comment]
I never tested with Python-3.6. Only up to 3.5. In case there is an easy fix, please send a pull request.

**Comment by nickpack** [comment]
The fix for this specific issue is:

`
diff --git a/shop/models/related.py b/shop/models/related.py
index 603ff32..8b1c4be 100644
--- a/shop/models/related.py
+++ b/shop/models/related.py
@@ -2,7 +2,7 @@
 from __future__ import unicode_literals

 import enum
-from six import with_metaclass, string_types
+from six import add_metaclass, with_metaclass, string_types
 from django.db import models
 from django.utils.six import python_2_unicode_compatible
 from django.utils.translation import ugettext_lazy
@@ -21,9 +21,9 @@ class ChoiceEnumMeta(enum.EnumMeta):
                 pass  # let the super method complain
         return super(ChoiceEnumMeta, cls).__call__(value, *args, **kwargs)

-
 @python_2_unicode_compatible
-class ChoiceEnum(with_metaclass(ChoiceEnumMeta, enum.Enum)):
+@add_metaclass(ChoiceEnumMeta)
+class ChoiceEnum(enum.Enum):
     """
     Utility class to handle choices in Django model fields
     """
`

The downside is that there are further errors after this - I am still looking at these.

**Comment by jrief** [comment]
The docs now state that you have to ``pip install enum34`` if running on Python2.
